// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBKV_nAFk1bZ_yg_KN9r3jkf0s5ukrdg',
    appId: '1:87016744992:web:eea03ae75ccd051c127445',
    messagingSenderId: '87016744992',
    projectId: 'enotes-flutter-yudantara',
    authDomain: 'enotes-flutter-yudantara.firebaseapp.com',
    storageBucket: 'enotes-flutter-yudantara.appspot.com',
    measurementId: 'G-0TRVZPTPSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHwes2S29N6SY-WjYITSgm20ME6ZSo08',
    appId: '1:87016744992:android:76bf0c8d10bdbaa5127445',
    messagingSenderId: '87016744992',
    projectId: 'enotes-flutter-yudantara',
    storageBucket: 'enotes-flutter-yudantara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqaxym86qIZ3-BNLiwo8BVetFm-prExpw',
    appId: '1:87016744992:ios:2a7448569b38ee2b127445',
    messagingSenderId: '87016744992',
    projectId: 'enotes-flutter-yudantara',
    storageBucket: 'enotes-flutter-yudantara.appspot.com',
    iosBundleId: 'id.yudantara.eNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqaxym86qIZ3-BNLiwo8BVetFm-prExpw',
    appId: '1:87016744992:ios:a564a93f3f199f45127445',
    messagingSenderId: '87016744992',
    projectId: 'enotes-flutter-yudantara',
    storageBucket: 'enotes-flutter-yudantara.appspot.com',
    iosBundleId: 'id.yudantara.eNotes.RunnerTests',
  );
}
